### PR TITLE
Not a pull request - suggestion for blog comments

### PR DESCRIPTION
**Pull request by qwertychouskie**
I sent this on Twitter but it probably got lost in the aether,

Since Disqus was not working for your blog, consider https://talk.hyvor.com as it has no ads and I've heard it's solid.  https://www.omglinux.com/ uses it on their site and said it's good, see comments of https://omglinux.com/kde-discover-flatpak-snap-permissions-gsoc/

### CODE REVIEW

**Comment by zmike** [comment]
Interesting. I'll check this out.

**Comment by zmike** [comment]
Hm hyvor seems neat, but I'm a bit concerned with the pricing. At the time of the omglinux posting (less than a year ago), the monthly rate was $5/month. The current monthly rate is $12/month. That's already more than I pay for the entire site, and who knows what it will be in a year.

The issue isn't the cost, it's the unknown pricing structure. You're right though, I should be looking into something here.

**Comment by rhysperry111** [comment]
There's [giscus](https://giscus.app) that adds comments to a site and uses GitHub discussions on the backend

**Comment by zmike** [comment]
Wow, I set up giscus in about 2 mins and it seems to actually do what it claims. Incredible.

**Comment by rhysperry111** [comment]
You might want to force it to use light mode. It seems to use the browser's preference (which your site doesn't - and so if the dark theme is preferred you end up with dark comments on a light site)
Screenshot_20230414-154953_Firefox

(and yes, apparently I am the *other* open-source-linux-nerd Rhys Perry)

**Comment by zmike** [comment]
hm yeah good point

**Comment by surendrajat** [comment]
How about [remark](https://remark42.com/)? It's pretty lightweight and not dependent on GitHub etc. But you'll have to self-host it somewhere.

**Comment by jasuarez** [comment]
I'm using [Isso](https://isso-comments.de/).

It stores the comments in a sqlite database.

**Comment by zmike** [comment]
I'm liking giscus so far, but I'll reopen if there's problems. Thanks everyone who suggested things!

**Pull request closed without merging**
